### ISSUE TITLE
Namespace change

### ISSUE THREAD

**Issue by weavejester** [liwp/again#1]
We should probably change the namespace from `again.core` to `listora.again`. It's a bit more specific, and we can get rid of the `core` part that really only exists to avoid single-part namespaces.

**Comment by ordnungswidrig** [comment]
:+1:

**Comment by liwp** [comment]
I appreciate the sentiment, but I'm closing this for a couple of reasons: i) I don't want to break the API for existing users just for cosmetic reasons, and ii) the future of the lib within the Listora org is uncertain at the moment, so I don't really want to tie the lib to that name.
